language: ruby
rvm:
- 2.2
- 2.1
- 2.0
- 1.9.3
sudo: required
services:
- docker
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y ansible
# Ansible 1.4.4 does not seem to play well with debian:stretch
script:
  - >
    wget -O- bit.ly/ansibletest | env
    DOCKER_IMAGES="centos:6 centos:7 fedora:20 fedora:24
    ubuntu:14.04 ubuntu:16.04 debian:7 debian:8"
    ANSIBLE_VERSIONS="1.4 2.1.0.0"
    sh

after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: change
    on_failure: change
    rooms:
      - secure: YG6xbYHp70y4cQrzx/Zal2uUujc32Fnh/sGRfgJkC2cjs2vFQvqc96cx0uB1dERKtl67TrCxO5jbtEVzw0RbSLHRJA5J5dPXNU5Sskjls8En4JY3MhU9rboKBaZNXHx0yJdmz8/oN9cP7z0otpNKz3ezmr8pqPOXAMbX2ZNSdETeV4MPT/edXkHL2483X40MJ4Fg61lGM/g6SzzjjQSIkZhmTriZJedsf+CVJNUWJlcV2DEVDj+WMhDVj5igh4qiwke2h2/f+RTq0XMXMWCBMgCdn5UYnQytMSHZMN4CXRcgh1kUUxJBJGqkmthQEfopEpWY/BYtupdL7ZTNeU1f4vaW2ad6YzR/97FYDj6qIzlEQdjzT30Owyj1Je/BBvq6JEJuQY4wbKZZFv0/6/FcuQz7qEmBaISKAR6N8kzg3PSuPsdNprlDhGQv8WA8q0bbGMK48LERjAzNArZeRRGaAWsNn9eizmimgukaNlDCBbBhu6TwCNBHHxtooH8WN6Ti6sEUzEmVSiBUuOTFik8xA19+ZlkCQzcoFwIghU5fz+kY/wh42comBiEPCaaiPo7OjDUVLaHtSC6C8dHjAoJWLrc9jGpD5/O/jNLpAg265izmOudwKYUsc6JugYBBNafVaDgvveDgfL4BenLRMvSjij0wIXTXx3wzPWZ27kn2jvk=
  email:
    recipients:
      secure: eH6UuF0d8lRkDraRNoMQBcgWWxrRkhWDqVUFkGu6Xr8zkGLW/jOefaRUIciDA9h64E565vRBFXp9+X8PJydj5ms3SaZEtkc2DnluGw7Yd/cyCsLfGzpPRIxTKux4bSvuh+jv32yDvcHLEXcQ3O9h5cJNqxNnLzDm3EviLP4TsiFHWwkU5ub9SHXbOx0kpRediPT1jf5PKET0iLkHEkjTiwWcfkkANqXbHyzPSX/dytLaKzLVJNwApNnoRwkAsev18MRRh43eaMyNZFycoNfVVKEOudtwN/oFPVsqiPml2wVmHFcdAnGGRw7FJzbqmHD0N3+1N23KF33DKdfP/rVYat4C7B9xL5LxBAT6YTb7GBC5kitL65Aa1cK1xiz9LyDQOsFHZSyOm+EJany+42quAeXgXCIB4bAGGVt5LqYxTmhyEUcFeTpIMgz1mL8FFybvMEaq3XqAqchh2biSbhgimiIhuKCIipo62UJb2KAMwi8eW+r5fdA2GCPKPFwW9htI6IkhVe7AhAzY6qyYfnwsZHw922odReJy2pJ39WRvlU1I/GpnrHswLcuEN+61nIVeDM1lUcSaP0xZmOcxMfmdyCiZ8L2QsKSvTs7UssfbBEyxkt97XOrCx7YhqKpCDnzrXz4C8MH61L02ib+TYZ8p3ShN9S9j882pci4PxyLI8Rk=
