---
# Needed to install gnupg
- name: apt-get update
  apt: update_cache=true cache_valid_time=3600
  sudo: yes

# gnupg gpg command is needed to download tor package key
- name: install gnupg
  apt: name=gnupg
  sudo: yes

- name: add tor key to apt-key
  apt_key:
    file: "{{tor_key_local_file}}"
  sudo: yes

- name: tor sources.list
  template: src=tor.list.j2 dest=/etc/apt/sources.list.d/tor.list
  register: sources_list_result
  sudo: yes

- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes
